sudo: false
language: python
cache: pip

matrix:
  include:
    - env: TOXENV=flake8
    - env: TOXENV=isort
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.4"
      env: TOXENV=py34
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=py37
      dist: xenial
      sudo: required

install: pip install tox
script: tox
